FROM node:alpine as build

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app
COPY package-lock.json /app
RUN npm ci --silent
COPY db.json ./
RUN npm install react-scripts@4.0.1 -g --silent

EXPOSE 8000

CMD ["npm", "run", "json"]